### ISSUE TITLE
Long column type

### ISSUE THREAD

**Issue by mecid** [TimotheeJeannin/ProviGen#36]
Please add Long for column type.

**Comment by TimotheeJeannin** [comment]
Hi @mecid, 

From the [SQLite documentation on types](https://www.sqlite.org/datatype3.html), there is only five types available (`NULL`, `INTEGER`, `REAL`, `TEXT`, `BLOB`). A long value is stored as an 8 byte `INTEGER`.

See this answer for more details : http://stackoverflow.com/questions/8672473/is-there-type-long-in-android-sql

**Comment by mecid** [comment]
@TimotheeJeannin thanks

**Comment by TimotheeJeannin** [comment]
You're welcome. :)
